export default {
    dashboard: '/dashboard',
    tickets: '/tickets',
    ideas: '/ideas',
    ideasTwo: '/ideas/two',
    ideasThree: '/ideas/three',
    PaymentList: '/PaymentList',
    FeedBack: '/FeedBack',
    articles: '/articles',
    TermAndCondition: '/TermAndCondition',
    settings: '/settings',
    PdfDetail: '/PdfDetail',
    UserList: '/UserList',
    AddAdmin: '/AddAdmin',
    AdminList: '/AdminList',
    login: '/login',
    signup: '/signup',
    forgotPassword: '/forgot_password',
    privacyPolicy: '/privacyPolicy',
    items: '/items',
    UserDetail: '/UserDetail',
    CustomerDetail: '/CustomerDetail',
    ViewDraft: '/ViewDraft',
    AddProduct: '/AddProduct',
    PriceSheet: '/PriceSheet'
};
